<?php
declare(strict_types=1);
namespace App\Language\Application;

final class SystemTranslationCatalog
{
 /** @return array<string,array{pl:string,en:string}> */
 public static function phrases():array{return [
  'common.save'=>['pl'=>'Zapisz','en'=>'Save'],'common.edit'=>['pl'=>'Edytuj','en'=>'Edit'],'common.delete'=>['pl'=>'Usuń','en'=>'Delete'],'common.cancel'=>['pl'=>'Anuluj','en'=>'Cancel'],'common.back'=>['pl'=>'Wróć','en'=>'Back'],'common.search'=>['pl'=>'Szukaj','en'=>'Search'],'common.add'=>['pl'=>'Dodaj','en'=>'Add'],'common.status'=>['pl'=>'Status','en'=>'Status'],'common.actions'=>['pl'=>'Akcje','en'=>'Actions'],'common.active'=>['pl'=>'Aktywny','en'=>'Active'],'common.inactive'=>['pl'=>'Nieaktywny','en'=>'Inactive'],'common.yes'=>['pl'=>'Tak','en'=>'Yes'],'common.no'=>['pl'=>'Nie','en'=>'No'],'common.created_at'=>['pl'=>'Utworzono','en'=>'Created at'],'common.updated_at'=>['pl'=>'Zaktualizowano','en'=>'Updated at'],
  'nav.dashboard'=>['pl'=>'Pulpit','en'=>'Dashboard'],'nav.pages'=>['pl'=>'Podstrony','en'=>'Pages'],'nav.menu'=>['pl'=>'Menu','en'=>'Menu'],'nav.users'=>['pl'=>'Użytkownicy','en'=>'Users'],'nav.configuration'=>['pl'=>'Konfiguracja','en'=>'Configuration'],'nav.email_templates'=>['pl'=>'Szablony e-mail','en'=>'Email templates'],'nav.newsletter'=>['pl'=>'Newsletter','en'=>'Newsletter'],'nav.languages'=>['pl'=>'Języki','en'=>'Languages'],'nav.file_manager'=>['pl'=>'Menedżer plików','en'=>'File manager'],'nav.logs'=>['pl'=>'Logi','en'=>'Logs'],'nav.open_site'=>['pl'=>'Otwórz stronę','en'=>'Open website'],'nav.logout'=>['pl'=>'Wyloguj','en'=>'Log out'],
  'front.home'=>['pl'=>'Strona główna','en'=>'Home'],'front.features'=>['pl'=>'Możliwości','en'=>'Features'],'front.how_it_works'=>['pl'=>'Jak to działa','en'=>'How it works'],'front.for_whom'=>['pl'=>'Dla kogo','en'=>'Who it is for'],'front.contact'=>['pl'=>'Kontakt','en'=>'Contact'],'front.login'=>['pl'=>'Zaloguj się','en'=>'Log in'],'front.start'=>['pl'=>'Rozpocznij','en'=>'Get started'],'front.back_home'=>['pl'=>'Wróć na stronę główną','en'=>'Back to homepage'],'front.need_help'=>['pl'=>'Potrzebujesz pomocy?','en'=>'Need help?'],
  'front.main_menu'=>['pl'=>'Menu główne','en'=>'Main menu'],'front.search'=>['pl'=>'Szukaj','en'=>'Search'],'front.open_menu'=>['pl'=>'Otwórz menu','en'=>'Open menu'],'front.tagline'=>['pl'=>'Nowoczesny, modułowy system zarządzania firmą.','en'=>'A modern, modular business management system.'],'front.rights'=>['pl'=>'Wszystkie prawa zastrzeżone.','en'=>'All rights reserved.'],'front.help_text'=>['pl'=>'Skontaktuj się z nami, jeśli potrzebujesz dodatkowych informacji.','en'=>'Contact us if you need any additional information.'],'front.page_caption'=>['pl'=>'Informacje i materiały przygotowane dla użytkowników Shopro.','en'=>'Information and resources prepared for Shopro users.'],
  'menu.translations'=>['pl'=>'Tłumaczenia','en'=>'Translations'],'menu.translation_saved'=>['pl'=>'Tłumaczenie pozycji menu zostało zapisane.','en'=>'The menu item translation has been saved.'],
  'auth.identifier'=>['pl'=>'Login lub adres e-mail','en'=>'Username or email address'],'auth.password'=>['pl'=>'Hasło','en'=>'Password'],'auth.sign_in'=>['pl'=>'Zaloguj się','en'=>'Sign in'],'auth.invalid_credentials'=>['pl'=>'Nieprawidłowy login lub hasło.','en'=>'Invalid username or password.'],
  'page.title'=>['pl'=>'Tytuł','en'=>'Title'],'page.slug'=>['pl'=>'Adres URL','en'=>'URL address'],'page.published'=>['pl'=>'Opublikowana','en'=>'Published'],'page.draft'=>['pl'=>'Szkic','en'=>'Draft'],'page.translations'=>['pl'=>'Tłumaczenia','en'=>'Translations'],'page.no_content'=>['pl'=>'Ta podstrona nie ma jeszcze treści.','en'=>'This page does not have content yet.'],
  'newsletter.subject'=>['pl'=>'Temat','en'=>'Subject'],'newsletter.recipients'=>['pl'=>'Odbiorcy','en'=>'Recipients'],'newsletter.send'=>['pl'=>'Wyślij','en'=>'Send'],'newsletter.resend'=>['pl'=>'Wyślij ponownie','en'=>'Send again'],'newsletter.unsubscribe'=>['pl'=>'Wypisz się','en'=>'Unsubscribe'],'newsletter.unsubscribe_done'=>['pl'=>'Adres został wypisany.','en'=>'The address has been unsubscribed.'],
  'language.name'=>['pl'=>'Nazwa języka','en'=>'Language name'],'language.locale'=>['pl'=>'Ustawienia regionalne','en'=>'Locale'],'language.currency'=>['pl'=>'Waluta','en'=>'Currency'],'language.default'=>['pl'=>'Język domyślny','en'=>'Default language'],'language.direction'=>['pl'=>'Kierunek tekstu','en'=>'Text direction'],
  'language.change'=>['pl'=>'Zmień język','en'=>'Change language'],'page.copy_base_template'=>['pl'=>'Zastosuj szablon języka głównego','en'=>'Use the primary language template'],'page.copy_base_template_help'=>['pl'=>'Możesz rozpocząć od identycznego układu jak w języku bazowym, a następnie przetłumaczyć jego treści.','en'=>'Start with the same layout as the primary language, then translate its content.'],
  'error.not_found'=>['pl'=>'Strona nie została znaleziona.','en'=>'Page not found.'],'error.server'=>['pl'=>'Wystąpił błąd serwera.','en'=>'A server error occurred.'],'validation.required'=>['pl'=>'To pole jest wymagane.','en'=>'This field is required.'],
 ];}
}
