<?php
declare(strict_types=1);
namespace App\Language\Application;

final class SystemTranslationCatalog
{
 /** @return array<string,array{pl:string,en:string}> */
 public static function phrases():array{return [
  'common.save'=>['pl'=>'Zapisz','en'=>'Save'],'common.edit'=>['pl'=>'Edytuj','en'=>'Edit'],'common.delete'=>['pl'=>'Usuń','en'=>'Delete'],'common.cancel'=>['pl'=>'Anuluj','en'=>'Cancel'],'common.back'=>['pl'=>'Wróć','en'=>'Back'],'common.search'=>['pl'=>'Szukaj','en'=>'Search'],'common.add'=>['pl'=>'Dodaj','en'=>'Add'],'common.status'=>['pl'=>'Status','en'=>'Status'],'common.actions'=>['pl'=>'Akcje','en'=>'Actions'],'common.active'=>['pl'=>'Aktywny','en'=>'Active'],'common.inactive'=>['pl'=>'Nieaktywny','en'=>'Inactive'],'common.yes'=>['pl'=>'Tak','en'=>'Yes'],'common.no'=>['pl'=>'Nie','en'=>'No'],'common.created_at'=>['pl'=>'Utworzono','en'=>'Created at'],'common.updated_at'=>['pl'=>'Zaktualizowano','en'=>'Updated at'],
  'nav.dashboard'=>['pl'=>'Pulpit','en'=>'Dashboard'],'nav.pages'=>['pl'=>'Podstrony','en'=>'Pages'],'nav.menu'=>['pl'=>'Menu','en'=>'Menu'],'nav.users'=>['pl'=>'Użytkownicy','en'=>'Users'],'nav.configuration'=>['pl'=>'Konfiguracja','en'=>'Configuration'],'nav.email_templates'=>['pl'=>'Szablony e-mail','en'=>'Email templates'],'nav.newsletter'=>['pl'=>'Newsletter','en'=>'Newsletter'],'nav.languages'=>['pl'=>'Języki','en'=>'Languages'],'nav.file_manager'=>['pl'=>'Menedżer plików','en'=>'File manager'],'nav.logs'=>['pl'=>'Logi','en'=>'Logs'],'nav.open_site'=>['pl'=>'Otwórz stronę','en'=>'Open website'],'nav.logout'=>['pl'=>'Wyloguj','en'=>'Log out'],
  'admin.main'=>['pl'=>'GŁÓWNE','en'=>'MAIN'],'admin.content_management'=>['pl'=>'ZARZĄDZANIE TREŚCIĄ','en'=>'CONTENT MANAGEMENT'],'admin.users_system'=>['pl'=>'UŻYTKOWNICY I SYSTEM','en'=>'USERS AND SYSTEM'],'admin.website'=>['pl'=>'WITRYNA','en'=>'WEBSITE'],'admin.close_menu'=>['pl'=>'Zamknij menu','en'=>'Close menu'],'admin.open_menu'=>['pl'=>'Otwórz menu','en'=>'Open menu'],'admin.panel_menu'=>['pl'=>'Menu panelu','en'=>'Admin menu'],'admin.panel'=>['pl'=>'Panel administracyjny','en'=>'Admin panel'],'admin.open_website'=>['pl'=>'Otwórz witrynę','en'=>'Open website'],'admin.development_version'=>['pl'=>'Wersja developerska','en'=>'Development version'],'admin.administrator'=>['pl'=>'Administrator','en'=>'Administrator'],
  'dashboard.greeting'=>['pl'=>'Dzień dobry','en'=>'Good morning'],'dashboard.lead'=>['pl'=>'Zarządzaj treścią swojej witryny z jednego miejsca.','en'=>'Manage your website content from one place.'],'dashboard.new_page'=>['pl'=>'Nowa podstrona','en'=>'New page'],'dashboard.all_pages'=>['pl'=>'Wszystkie podstrony','en'=>'All pages'],'dashboard.published'=>['pl'=>'Opublikowane','en'=>'Published'],'dashboard.drafts'=>['pl'=>'Szkice','en'=>'Drafts'],'dashboard.unpublished'=>['pl'=>'Nieopublikowane','en'=>'Unpublished'],'dashboard.active'=>['pl'=>'Aktywne','en'=>'Active'],'dashboard.quick_start'=>['pl'=>'SZYBKI START','en'=>'QUICK START'],'dashboard.create_better'=>['pl'=>'Twórz treści wygodniej','en'=>'Create content more easily'],'dashboard.create_help'=>['pl'=>'Dodawaj podstrony, publikuj je i zarządzaj adresami bez ingerencji w kod.','en'=>'Add and publish pages and manage their URLs without editing code.'],'dashboard.go_pages'=>['pl'=>'Przejdź do podstron','en'=>'Go to pages'],'dashboard.system_status'=>['pl'=>'STATUS SYSTEMU','en'=>'SYSTEM STATUS'],'dashboard.online'=>['pl'=>'Online','en'=>'Online'],'dashboard.application'=>['pl'=>'Aplikacja','en'=>'Application'],'dashboard.environment'=>['pl'=>'Środowisko','en'=>'Environment'],'dashboard.development'=>['pl'=>'Developerskie','en'=>'Development'],'dashboard.cms_active'=>['pl'=>'Aktywny','en'=>'Active'],
  'pages.heading'=>['pl'=>'Podstrony','en'=>'Pages'],'pages.lead'=>['pl'=>'Twórz i publikuj zawartość widoczną w witrynie.','en'=>'Create and publish content displayed on your website.'],'pages.list'=>['pl'=>'Lista podstron','en'=>'Page list'],'pages.item'=>['pl'=>'element','en'=>'item'],'pages.items'=>['pl'=>'elementów','en'=>'items'],'pages.page'=>['pl'=>'Podstrona','en'=>'Page'],'pages.url'=>['pl'=>'Adres URL','en'=>'URL address'],'pages.updated'=>['pl'=>'Aktualizacja','en'=>'Updated'],'pages.home'=>['pl'=>'strona główna','en'=>'homepage'],'pages.system'=>['pl'=>'strona systemowa','en'=>'system page'],'pages.open'=>['pl'=>'Otwórz','en'=>'Open'],'pages.duplicate'=>['pl'=>'Duplikuj','en'=>'Duplicate'],'pages.delete_confirm'=>['pl'=>'Usunąć podstronę?','en'=>'Delete this page?'],'pages.empty'=>['pl'=>'Nie utworzono jeszcze żadnej podstrony.','en'=>'No pages have been created yet.'],
  'front.home'=>['pl'=>'Strona główna','en'=>'Home'],'front.features'=>['pl'=>'Możliwości','en'=>'Features'],'front.how_it_works'=>['pl'=>'Jak to działa','en'=>'How it works'],'front.for_whom'=>['pl'=>'Dla kogo','en'=>'Who it is for'],'front.contact'=>['pl'=>'Kontakt','en'=>'Contact'],'front.login'=>['pl'=>'Zaloguj się','en'=>'Log in'],'front.start'=>['pl'=>'Rozpocznij','en'=>'Get started'],'front.back_home'=>['pl'=>'Wróć na stronę główną','en'=>'Back to homepage'],'front.need_help'=>['pl'=>'Potrzebujesz pomocy?','en'=>'Need help?'],
  'front.main_menu'=>['pl'=>'Menu główne','en'=>'Main menu'],'front.search'=>['pl'=>'Szukaj','en'=>'Search'],'front.open_menu'=>['pl'=>'Otwórz menu','en'=>'Open menu'],'front.tagline'=>['pl'=>'Nowoczesny, modułowy system zarządzania firmą.','en'=>'A modern, modular business management system.'],'front.rights'=>['pl'=>'Wszystkie prawa zastrzeżone.','en'=>'All rights reserved.'],'front.help_text'=>['pl'=>'Skontaktuj się z nami, jeśli potrzebujesz dodatkowych informacji.','en'=>'Contact us if you need any additional information.'],'front.page_caption'=>['pl'=>'Informacje i materiały przygotowane dla użytkowników Shopro.','en'=>'Information and resources prepared for Shopro users.'],
  'front.preview_aria'=>['pl'=>'Podgląd panelu Shopro','en'=>'Shopro dashboard preview'],'front.preview_greeting'=>['pl'=>'Dzień dobry','en'=>'Good morning'],'front.preview_new_page'=>['pl'=>'Nowa podstrona','en'=>'New page'],'front.preview_pages'=>['pl'=>'Podstrony','en'=>'Pages'],'front.preview_published'=>['pl'=>'Opublikowane','en'=>'Published'],'front.preview_drafts'=>['pl'=>'Szkice','en'=>'Drafts'],'front.preview_activity'=>['pl'=>'Aktywność','en'=>'Activity'],'front.preview_last_days'=>['pl'=>'Ostatnie 7 dni','en'=>'Last 7 days'],'front.preview_processes'=>['pl'=>'Aktywne procesy','en'=>'Active processes'],'front.preview_system_ok'=>['pl'=>'System działa','en'=>'System operational'],'front.preview_services_ok'=>['pl'=>'Wszystkie usługi aktywne','en'=>'All services active'],'front.preview_your_system'=>['pl'=>'TWÓJ SYSTEM','en'=>'YOUR SYSTEM'],'front.preview_easy'=>['pl'=>'Prosty w obsłudze.','en'=>'Easy to use.'],'front.preview_ready'=>['pl'=>'Gotowy na rozwój.','en'=>'Ready to grow.'],
  'maintenance.title'=>['pl'=>'Przerwa techniczna','en'=>'Maintenance'],'maintenance.kicker'=>['pl'=>'PRZERWA TECHNICZNA','en'=>'SCHEDULED MAINTENANCE'],'maintenance.heading'=>['pl'=>'Wracamy wkrótce','en'=>'We will be back soon'],'maintenance.ends'=>['pl'=>'Planowane zakończenie:','en'=>'Expected completion:'],
  'menu.translations'=>['pl'=>'Tłumaczenia','en'=>'Translations'],'menu.translation_saved'=>['pl'=>'Tłumaczenie pozycji menu zostało zapisane.','en'=>'The menu item translation has been saved.'],
  'auth.identifier'=>['pl'=>'Login lub adres e-mail','en'=>'Username or email address'],'auth.password'=>['pl'=>'Hasło','en'=>'Password'],'auth.sign_in'=>['pl'=>'Zaloguj się','en'=>'Sign in'],'auth.invalid_credentials'=>['pl'=>'Nieprawidłowy login lub hasło.','en'=>'Invalid username or password.'],
  'page.title'=>['pl'=>'Tytuł','en'=>'Title'],'page.slug'=>['pl'=>'Adres URL','en'=>'URL address'],'page.published'=>['pl'=>'Opublikowana','en'=>'Published'],'page.draft'=>['pl'=>'Szkic','en'=>'Draft'],'page.translations'=>['pl'=>'Tłumaczenia','en'=>'Translations'],'page.no_content'=>['pl'=>'Ta podstrona nie ma jeszcze treści.','en'=>'This page does not have content yet.'],
  'newsletter.subject'=>['pl'=>'Temat','en'=>'Subject'],'newsletter.recipients'=>['pl'=>'Odbiorcy','en'=>'Recipients'],'newsletter.send'=>['pl'=>'Wyślij','en'=>'Send'],'newsletter.resend'=>['pl'=>'Wyślij ponownie','en'=>'Send again'],'newsletter.unsubscribe'=>['pl'=>'Wypisz się','en'=>'Unsubscribe'],'newsletter.unsubscribe_done'=>['pl'=>'Adres został wypisany.','en'=>'The address has been unsubscribed.'],
  'language.name'=>['pl'=>'Nazwa języka','en'=>'Language name'],'language.locale'=>['pl'=>'Ustawienia regionalne','en'=>'Locale'],'language.currency'=>['pl'=>'Waluta','en'=>'Currency'],'language.default'=>['pl'=>'Język domyślny','en'=>'Default language'],'language.direction'=>['pl'=>'Kierunek tekstu','en'=>'Text direction'],
  'language.change'=>['pl'=>'Zmień język','en'=>'Change language'],'page.copy_base_template'=>['pl'=>'Zastosuj szablon języka głównego','en'=>'Use the primary language template'],'page.copy_base_template_help'=>['pl'=>'Możesz rozpocząć od identycznego układu jak w języku bazowym, a następnie przetłumaczyć jego treści.','en'=>'Start with the same layout as the primary language, then translate its content.'],
  'error.not_found'=>['pl'=>'Strona nie została znaleziona.','en'=>'Page not found.'],'error.server'=>['pl'=>'Wystąpił błąd serwera.','en'=>'A server error occurred.'],'validation.required'=>['pl'=>'To pole jest wymagane.','en'=>'This field is required.'],
 ];}
}
