<?php
declare(strict_types=1);
namespace App\Cms\Presentation\Http\Admin;
use App\Cms\Application\PageRevisionManager;use App\Cms\Application\UrlRedirectManager;use App\Cms\Domain\Entity\Page;use App\Cms\Infrastructure\Persistence\Doctrine\PageRepository;use App\Cms\Infrastructure\Persistence\Doctrine\PageRevisionRepository;use App\Identity\Domain\Entity\AdminUser;use App\Language\Application\SystemTranslator;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\HttpFoundation\Response;use Symfony\Component\Routing\Attribute\Route;use Symfony\Component\Security\Http\Attribute\IsGranted;
#[Route('/admin/pages/{id}/revisions',requirements:['id'=>'\d+'])]#[IsGranted('ROLE_EDITOR')]
final class PageRevisionController extends AbstractController
{
 public function __construct(private readonly SystemTranslator $translator){}
 #[Route('',name:'admin_page_revision_index',methods:['GET'])]public function index(Page $page,PageRevisionRepository $repository,PageRevisionManager $manager):Response{$revisions=$repository->forPage($page);$rows=[];foreach($revisions as $index=>$revision)$rows[]=['revision'=>$revision,'changes'=>$manager->changes($revision,$revisions[$index+1]??null)];return $this->render('admin/page/revisions.html.twig',['page'=>$page,'rows'=>$rows]);}
 #[Route('/{revisionId}/restore',name:'admin_page_revision_restore',requirements:['revisionId'=>'\d+'],methods:['POST'])]public function restore(Page $page,int $revisionId,Request $request,PageRevisionRepository $repository,PageRevisionManager $manager,PageRepository $pages,UrlRedirectManager $redirects,EntityManagerInterface $em):Response{$revision=$repository->find($revisionId);if(!$revision||$revision->getPage()->getId()!==$page->getId())throw $this->createNotFoundException();if(!$this->isCsrfTokenValid('restore-revision-'.$revisionId,(string)$request->request->get('_token')))return $this->redirectToRoute('admin_page_revision_index',['id'=>$page->getId()]);$oldSlug=$page->getSlug();$em->getConnection()->beginTransaction();try{$manager->restore($page,$revision);$pages->save($page);if($oldSlug!==$page->getSlug())$redirects->registerSlugChange($oldSlug,$page->getSlug(),$page->isHomePage());$user=$this->getUser();$manager->snapshot($page,$user instanceof AdminUser?$user:null);$em->getConnection()->commit();$this->addFlash('success',$this->translator->translate('revision.restored'));}catch(\Throwable $exception){if($em->getConnection()->isTransactionActive())$em->getConnection()->rollBack();throw $exception;}return $this->redirectToRoute('admin_page_edit',['id'=>$page->getId()]);}
}
